version: '3.30'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: 'blog'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    networks:
      - webapi_network
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - webapi_network
networks:
  webapi_network:
    driver: bridge 