// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/object_storage/object_storage.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=./pkg/object_storage/object_storage.go -destination=./mocks/object_storage_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	object_storage "blog/pkg/object_storage"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepository is a mock of StorageRepository interface.
type MockStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepositoryMockRecorder
}

// MockStorageRepositoryMockRecorder is the mock recorder for MockStorageRepository.
type MockStorageRepositoryMockRecorder struct {
	mock *MockStorageRepository
}

// NewMockStorageRepository creates a new mock instance.
func NewMockStorageRepository(ctrl *gomock.Controller) *MockStorageRepository {
	mock := &MockStorageRepository{ctrl: ctrl}
	mock.recorder = &MockStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepository) EXPECT() *MockStorageRepositoryMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockStorageRepository) DeleteFile(ctx context.Context, bucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, bucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockStorageRepositoryMockRecorder) DeleteFile(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockStorageRepository)(nil).DeleteFile), ctx, bucketName, objectName)
}

// GetObjectURL mocks base method.
func (m *MockStorageRepository) GetObjectURL(ctx context.Context, bucketName, objectName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectURL", ctx, bucketName, objectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectURL indicates an expected call of GetObjectURL.
func (mr *MockStorageRepositoryMockRecorder) GetObjectURL(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectURL", reflect.TypeOf((*MockStorageRepository)(nil).GetObjectURL), ctx, bucketName, objectName)
}

// UploadFile mocks base method.
func (m *MockStorageRepository) UploadFile(ctx context.Context, bucketName string, object object_storage.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, bucketName, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockStorageRepositoryMockRecorder) UploadFile(ctx, bucketName, object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockStorageRepository)(nil).UploadFile), ctx, bucketName, object)
}
